### ISSUE TITLE
deployment in AWS 

### ISSUE THREAD

**Issue by ChristianAdam** [mathiasbader/techupdate#3]

**Comment by amueller0011stad** [comment]
Die Anwendung ist deployed unter http://ec2-52-59-213-218.eu-central-1.compute.amazonaws.com:8090/corebanking/

Beipielrequest:
http://ec2-52-59-213-218.eu-central-1.compute.amazonaws.com:8090/corebanking/corebanking/banks/listWithDs

Die originalen Requests müssen noch  auf die Datasource umgestellt werden.
